language: node_js
node_js:
  - 6.10.3
services: postgresql
before_script:
  - psql -c 'create database pg_bump_test;' -U postgres
  - export PGDATABASE=pg_bump_test
install:
  - npm install
  - npm install -g codecov
script:
  - npm run cover
  - codecov
